services:
  - docker
addons:
  ssh_known_hosts: cloud.shu.xn--io0a7i

jobs:
  include:
    - stage: build
      language: minimal
      script:
        - docker build . -t shu-teacher
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag shu-teacher $DOCKER_USERNAME/shu-teacher:$TRAVIS_BUILD_ID
        - docker push $DOCKER_USERNAME/shu-teacher
    - stage: deploy
      language: minimal
      before_install:
        - openssl aes-256-cbc -K $encrypted_ebfa248821c6_key -iv $encrypted_ebfa248821c6_iv
          -in deploy_rsa.enc -out deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_rsa
        - ssh-add ./deploy_rsa
      script:
        - ssh -i ./deploy_rsa root@cloud.shu.xn--io0a7i changeImage.sh teacher $DOCKER_USERNAME/shu-teacher:$TRAVIS_BUILD_ID
